pool: Default
trigger: none 
variables:
  WORK_DIR: $(System.DefaultWorkingDirectory)/Environment/dev
  SERVICE_CONNECTION: corp-dev-01-sp

parameters:
- name: Scannining karna hey?
  displayName: Scanning
  type: boolean
  default: false
 
stages:

- stage: PreCommit
  displayName: Pre-Commit / Static Analysis Stage
  pool: Default
  jobs: 
  - job: TerraformValidate
    displayName: Terraform Validate
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(WORK_DIR)
        backendServiceArm: $(SERVICE_CONNECTION)
        backendAzureRmStorageAccountName: 'devopsinsidersstate'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'  
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: $(WORK_DIR)

  - job: TerraformFmt
    dependsOn: TerraformValidate
    displayName: Terraform Fmt
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'custom'
        environmentServiceNameAzureRM: $(SERVICE_CONNECTION)
        workingDirectory: $(WORK_DIR)
        outputTo: 'console'
        customCommand: 'fmt'

  - job: tfsec
    dependsOn: TerraformFmt
    displayName: TfSec Scan
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        dir: $(WORK_DIR)

  - job: tflint
    dependsOn: tfsec
    displayName: TFLint
    steps:
    - task: PowerShell@2
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: |
          winget install TerraformLinters.tflint     
          ls   
          tflint
        errorActionPreference: 'continue'        
        workingDirectory: $(WORK_DIR)

- stage: costStage
  dependsOn: PreCommit
  displayName: Cost & Impact Assessment Stage
  jobs: 
  - job: InfraCost
    displayName: InfraCost
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'infracost breakdown --path=.'
        workingDirectory: $(WORK_DIR)

- stage: plan
  displayName: Plan & Review Stage
  jobs: 
  - job: TerraformPlan
    displayName: Terraform Plan
    pool: Default
    steps: 
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(WORK_DIR)
        backendServiceArm: $(SERVICE_CONNECTION)
        backendAzureRmStorageAccountName: 'devopsinsidersstate'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(WORK_DIR)
        environmentServiceNameAzureRM: $(SERVICE_CONNECTION)

- stage: approval
  dependsOn: plan
  displayName: Approval & Governance Stage
  jobs:
  - job: ManualApproval
    displayName: Manual Approval
    pool: server
    steps: 
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'falana@gmail.com'

- stage: apply
  dependsOn: approval
  displayName: Deploy / Apply Stage
  jobs:
  - job: TerraformApply
    displayName: Terraform Apply
    pool: Default
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(WORK_DIR)
        backendServiceArm: $(SERVICE_CONNECTION)
        backendAzureRmStorageAccountName: 'devopsinsidersstate'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'  
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: $(WORK_DIR)
        environmentServiceNameAzureRM: $(SERVICE_CONNECTION)
